### ISSUE TITLE
启动proxy_pool之后报错：Exception: Install 'email_validator' for email validation support.

### ISSUE THREAD

**Issue by hustszh** [1again/ProxyPool#20]
按说明文档启动开发环境，出现以下错误，请问一下是本地python环境问题吗？
本地安装了email_validator还是同样报错。
本地python环境：3.7

Traceback (most recent call last):
  File "Src/Run/main.py", line 69, in <module>
    main()
  File "Src/Run/main.py", line 66, in main
    WebManager.run()
  File "Src/Web/WebManager.py", line 60, in run
    start_app()
  File "Src/Web/WebManager.py", line 49, in start_app
    from Web.admin import admin
  File "Src/Web/admin/__init__.py", line 1, in <module>
    from . import admin
  File "Src/Web/admin/admin.py", line 1, in <module>
    from .views import ProxyView, SettingView, FetcherView, ProxyPoolAdminIndexView
  File "Src/Web/admin/views.py", line 4, in <module>
    from flask_security import current_user
  File "/usr/local/lib/python3.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/usr/local/lib/python3.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/usr/local/lib/python3.7/site-packages/flask_security/forms.py", line 69, in <module>
    email_validator = Email(message='INVALID_EMAIL_ADDRESS')
  File "/usr/local/lib/python3.7/site-packages/wtforms/validators.py", line 332, in __init__
    raise Exception("Install 'email_validator' for email validation support.")
Exception: Install 'email_validator' for email validation support.

**Comment by ozhiwei** [comment]
从报错信息来看, 如果没有使用docker的话
可以执行`pip install email-validator`来安装依赖

**Comment by hustszh** [comment]
我是按照说明文档使用docker运行的。
email-validator在本地也是安装的了：
Requirement already satisfied: email-validator in /root/anaconda3/lib/python3.7/site-packages (1.1.0)

**Comment by ozhiwei** [comment]
你如果使用的是docker就和本地的python版本没有关系了.

**Comment by takeTrace** [comment]
requirement.txt 加上 email-validator?

**Comment by ozhiwei** [comment]
> requirement.txt 加上 email-validator?

你也遇到了? 如果使用docker, 应该不会碰到这种问题啊.

**Comment by jasonlee529** [comment]
docker build的过程会抛出email-validator的问题。
我是通过添加requirements.txt解决的。
